[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[plugins]]
package = "netlify-plugin-hashfiles"

  [plugins.inputs]
  # An array of glob patterns for pages on your site. Recursive traversal will start from these
  entryPoints = [
    "*.html"
  ]

  # Directory where content-addressable files are moved and immutable cache-headers are set
  staticDir = "/static/"

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"