baseURL = "https://paisley-digital.netlify.com/"
disableLanguages = []
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Paisley Digital"
[Languages.en]
contentDir = "content/english"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
home = "Accueil"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[menu.main]]
URL = "about"
name = "About Us"
weight = 1
[[menu.main]]
URL = "services"
name = "Service"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "team"
name = "Team"
weight = 4
[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 5
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax HTML5 Template"
google_analitycs_id = ""
logo = "images/logo-gradiant-01.png.png"
post_share = true
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/logo-paisley-3.png"
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
